### ISSUE TITLE
Cannot launch 1.8.9 instance

### ISSUE THREAD

**Issue by whyhea1** [modrinth/code#4843]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [x] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

0.10.21

### What operating systems are you seeing the problem on?

MacOS

### Describe the bug

Cannot launch 1.8.9 instance, tested forge and vanilla

### Steps to reproduce

1. Create 1.8.9 instance
2. Launch

### Expected behavior

Error launching Minecraft: Could not canonicalize library path /Users/xxx/Library/Application Support/ModrinthApp/meta/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5.jar: No such file or directory (os error 2)

### Additional context

I went through file system and it seems that there is indeed twitch-6.5.jar and the directory is /Users/xxx/Library/Application Support/ModrinthApp/meta/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar

**Comment by whyhea1** [comment]
I then tried renaming the folder and the jar file into twitch-platform but then the error message changed into this:
Error launching Minecraft: Could not canonicalize library path /Users/xxx/Library/Application Support/ModrinthApp/meta/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar: No such file or directory (os error 2)

**Comment by whyhea1** [comment]
I changed it back and its now back to the previous error message

**Comment by Hallskii** [comment]
Hey we should have already fixed this and it works for me in the app! Going to close, but LMK if it still doesn't work for you

**Comment by mrlork** [comment]
It is not fixed, it is doing this to me

**Comment by whyhea1** [comment]
> Hey we should have already fixed this and it works for me in the app! Going to close, but LMK if it still doesn't work for you

Not fixed for me either

**Comment by Hallskii** [comment]
Reopened, looking into now

**Comment by aecsocket** [comment]
Hi, having a look at this issue now - I've got a fresh install of the Modrinth app, created vanilla and Forge 1.8.9 instances, and pressed the play button to launch the game. Both instances launch and work without problems, so perhaps this is a platform-dependent bug? It may also be related to https://github.com/modrinth/code/issues/4589 which is already fixed.

To confirm, are you trying to launch an existing instance, or creating a fresh instance and launching that?

**Comment by whyhea1** [comment]
Launching existing instances

**Comment by mrlork** [comment]
I have tried launching every kind of instance, I've also deleted all of the modrinth files and redownloaded. It won't open any instance because it says: Error launching Minecraft: Could not canonicalize library path /Users/lorcanwheeler/Library/Application Support/ModrinthApp/meta/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5.jar: No such file or directory (os error 2)

**Comment by mrlork** [comment]
I figured it out, you have to create a file for what is missing, so if your missing twitch-platform/6.5/twitch-platform-6.5.jar. I just downloaded the jar from an index and copy and pasted it into the new files and it worked.

**Comment by ghost** [comment]
I am still having this issue on app version 0.10.24 and macOS 14.5.0 (M1), even after deleting modrinth and the modrinthapp folder in application support and redownloading the dmg

**Comment by Hallskii** [comment]
We looked into this and its reproducible on other launcher like Prism. I think its something wrong with that specific Forge version and we couldn't find a clear solution

**Comment by GitHubber1000** [comment]
I'm getting the same error trying to launch forge 1.7.10 on m3 mac

**Comment by Hallskii** [comment]
@GitHubber1000 I can't reproduce, instance creation and launching the client both worked. What version of macOS?

**Comment by malte9799** [comment]
I got the same issue.

Trying to run mc forge 1.8.9
macOS 26.2 on M1 Pro Chip

already tried this, but didn't work.. https://discord.com/channels/734077874708938864/1462810685661511794/1462931552706105548

If you need any logs or something just lmk

**Comment by malte9799** [comment]
Ohh I got it working..

1. download https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar
2. open finder, go to `~/Library/Application Support/ModrinthApp/meta/libraries`
3. create the folders (if they dont exist): `~/Library/Application Support/ModrinthApp/meta/libraries/tv/twitch/twitch-platform/6.5/`
and then, move the downloaded jar to the last directory (tv/twitch/**twitch-platform**/6.5)
4. rename `twitch-platform-6.5-natives-osx.jar` to `twitch-platform-6.5.jar`

**Comment by Steveminecraftreal** [comment]
didnt work for me i still get the same error
